groups:
  - name: ml_application_alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(model_prediction_requests_total{status="error"}[5m])) / sum(rate(model_prediction_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High prediction error rate"
          description: "Prediction error rate is > 10%"

      - alert: SlowPredictionResponse
        expr: histogram_quantile(0.95, sum(rate(model_prediction_duration_seconds_bucket[5m])) by (le, model_version)) > 1.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow prediction response"
          description: "95th percentile response time exceeds 1s"

      - alert: HighMemoryUsage
        expr: app_memory_usage_bytes / 1024 / 1024 / 1024 > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage exceeds 1.5 GB"

      - alert: StalledTraining
        expr: increase(training_epochs_total[15m]) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Training stalled"
          description: "No training metrics update for 15 mins"
